version: 2

sources:
  - name: employee
    database: DBT_DB
    schema: PUBLIC
    tables:
      - name: EMPLOYEE_RAW
  - name: customer
    database: DBT_DB
    schema: PUBLIC
    tables:
      - name: CUSTOMER_SRC